  name: Create Release File
  on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
  jobs:
      gradle:
          name: Create Binary File and Upload to Release
          runs-on: ubuntu-latest
          steps:
              - name: Checkout
                uses: actions/checkout@v2
              - name: Setup JAVA 15
                uses: actions/setup-java@v1
                with:
                    java-version: 15
              - name: Gradle Build
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: buildPlugin
              - name: Upload Release
                uses: softprops/action-gh-release@v1
                with:
                    files: build/mirai/*.mirai.jar
                    tag_name: 0.1.0